name: scroll_shadow_container
description: Dynamically appearing shadows on top or bottom of a scrollable area
version: 2.1.1+2
repository: https://github.com/nuc134r/scroll_shadow_container

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
